server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
  allowed-clock-skew-seconds: 120


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

app:
  mail:
    from: ${MAIL_FROM:no-reply@ripple.dev}

  email:
    code-ttl-seconds: ${EMAIL_CODE_TTL_SECONDS:600}
    cooldown-seconds: ${EMAIL_CODE_COOLDOWN_SECONDS:30}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,X-Device-Id}
    exposed-headers: ${CORS_EXPOSED_HEADERS:Authorization}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

