server:
  port: ${SERVER_PORT}
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store: ${SSL_KEY_STORE}
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}

spring:
  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        applicationName: Ripple

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL}
    show-sql: ${JPA_SHOW_SQL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: ${REDIS_REPOSITORIES_ENABLED}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}
      mail.smtp.starttls.required: ${MAIL_SMTP_STARTTLS_REQUIRED}
      mail.smtp.connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT}
      mail.smtp.timeout: ${MAIL_SMTP_TIMEOUT}
      mail.smtp.writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
  allowed-clock-skew-seconds: ${JWT_ALLOWED_CLOCK_SKEW_SECONDS}

logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL}
    org.hibernate.type: ${LOG_LEVEL_HIBERNATE_TYPE}
    com.zaxxer.hikari.HikariConfig: ${LOG_LEVEL_HIKARI_CONFIG}
    com.zaxxer.hikari: ${LOG_LEVEL_HIKARI}
    org.springframework.boot.context.config: ${LOG_LEVEL_SPRING_CONFIG}

app:
  mail:
    from: ${MAIL_FROM}

  email:
    code-ttl-seconds: ${EMAIL_CODE_TTL_SECONDS}
    cooldown-seconds: ${EMAIL_CODE_COOLDOWN_SECONDS}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    exposed-headers: ${CORS_EXPOSED_HEADERS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}

cdn:
  base-url: ${CDN_BASE_URL}

auth:
  cookie:
    name: __Secure-RT
    path: /api/auth/refresh
    same-site: None
    secure: ${COOKIE_SECURE}
    http-only: true
    domain: ${COOKIE_DOMAIN}
