name: Deploy Ripple Backend to EC2 via GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ripple-ec2-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ripple-back:latest
            ghcr.io/${{ github.repository_owner }}/ripple-back:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # 0) AWS 자격 구성 (Secrets 사용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 1) 러너 퍼블릭 IP를 /32로 SG:22에 임시 허용
      - name: Allow runner IP on SG:22
        id: ipopen
        shell: bash
        run: |
          RUNNER_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')
          echo "runner_ip=$RUNNER_IP" >> "$GITHUB_OUTPUT"
          aws ec2 authorize-security-group-ingress \
            --group-id "${{ secrets.EC2_SG_ID }}" \
            --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${RUNNER_IP}/32,Description=gh-actions-temp}]" \
          || true

      # 2) SSH로 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            # GHCR가 private이면 로그인 (public이면 생략됨)
            if [ -n "${{ secrets.GHCR_READ_TOKEN }}" ]; then
              echo "${{ secrets.GHCR_READ_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            fi

            cd ~/deploy
            test -f docker-compose.yml || { echo "docker-compose.yml 없음"; exit 1; }
            test -f .env || { echo ".env 없음"; exit 1; }

            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
            docker image prune -f
            docker ps

      # 3) 허용 해제 (항상 실행)
      - name: Revoke runner IP on SG:22
        if: always()
        shell: bash
        run: |
          RUNNER_IP="${{ steps.ipopen.outputs.runner_ip }}"
          if [ -n "$RUNNER_IP" ]; then
            aws ec2 revoke-security-group-ingress \
              --group-id "${{ secrets.EC2_SG_ID }}" \
              --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${RUNNER_IP}/32}]" \
            || true
          fi
